version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=8080
    command: ["bundle", "exec", "ruby", "app.rb", "-o", "0.0.0.0"]
