version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=8080
      - SSE_TIMEOUT_SEC=5
      - DISCORD_WAIT_TIMEOUT_SEC=20
      - HTTP_OPEN_TIMEOUT_SEC=3
      - HTTP_READ_TIMEOUT_SEC=3
    command: ["bundle", "exec", "ruby", "app.rb", "-o", "0.0.0.0"]
