version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    develop:
      watch:
        - path: .
          target: /usr/src/app
          action: sync
          ignore:
            - Gemfile.lock
    env_file:
      - .env
    environment:
      - PORT=8080
      - LOG_LEVEL=DEBUG
